SkyTemple/skytemple

setup.py

They weren't installed otherwise.

added .css and .glade file in setup.py

---

skytemple/module/dungeon/controller/floor.py

I have also simplified the function a bit.
I know the function works in my own parser (implemented in another language), but since I can't test this myself I can't guarantee that it will work in Python as well, so make sure to test it first.
If it works, it should also fix #28.

Fix relative weight calculation

---

skytemple/module/misc_graphics/controller/wte_wtu.glade
skytemple/module/misc_graphics/controller/wte_wtu.py

Based on pull request Skytemple/skytemple-files#24.
- Identifier boxes have been removed and replaced by a description of the current image mode, the size and the actual dimensions of the WTE image.
- When importing, you can now choose which image mode to use and if the palette will be included into the file; actual dimensions are computed from the imported image size.
- You can also see palette variants for some WTE files (like frames or dungeons UI).
- Selecting WTU entries shows rectangles representing them on the WTE image.
This pull request and the other one should fix #56.

Support for WTU/WTE files

---

skytemple/module/dungeon/controller/fixed.glade
skytemple/module/dungeon/controller/fixed.py
skytemple/module/dungeon/controller/fixed_rooms.py
skytemple/module/dungeon/module.py

Related to Skytemple/skytemple-files#25
- The UI now uses the enumeration from skytemple-files to display the spawn type description.
- I renamed the unknown boolean 10 in fixed floor properties according to the pull request above.
- Some other minor fixes, like the switch for unknown boolean 8 not working because of some typo.

Improving fixed floors and monster spawns types.

---

skytemple/module/portrait/controller/portrait.py

Now, it also displays an error for each portrait that caused an error.
This is important to know which portrait(s) exactly caused the error when importing them (mainly for invalid compressed size, check Skytemple/skytemple-files#32).

 Display one error per portrait when importing via SpriteBot sheets

---

skytemple/module/dungeon/controller/floor.py
skytemple/module/dungeon/module.py
skytemple/module/dungeon_graphics/controller/tileset.py

Some fixes about marking items as modified: 
- the mappa_g data wasn't synced with the mappa data when only the tileset ID or the fixed floor ID was changed
- the method mark_as_modified from the dungeon_graphics module needed one more argument (is_background) than what was passed by the tileset controller, which caused an error preventing the tileset being marked as modified

Minor fixes when marking items as modified

---

skytemple/module/lists/controller/world_map.py
skytemple/module/lists/world_map_drawer.py

- Builds the correct location names list for markers.
- Use the map id from the level list when loading the map background instead of the level id (which was renamed from map_id to level_id to avoid confusion)
It should be merged with Skytemple/skytemple-files#34 to work.

Fix world map component

---

skytemple/module/misc_graphics/controller/zmappat.glade
skytemple/module/misc_graphics/controller/zmappat.py
skytemple/module/misc_graphics/module.py

See Skytemple/skytemple-files#37.
- Support for viewing zmappat files (under "Misc. Graphics" section).
- UI Support for exporting zmappat data to image files.
- UI Support for importing zmappat data from image files.
- Some explanations about how this file works.
Uses the pull request mentioned above to work.

Adding primitive support for zmappat file

---

skytemple/module/monster/controller/monster.py
skytemple/module/monster/module.py

Some fixes related to the monster data:
- Invalid max_tile_slots_needed calculation
- Add calls to refresh to refresh the tree when needed (when exporting to other pokémon and changing the gender; should fix #71)

Monster data: minor fixes

---

skytemple/module/monster/controller/monster.py

A small improvement to sort the ability list by name in the combo box when editing the pokémon data, because it's hard to find a specific ability in a 100+ unsorted abilities list.

Sort the abilities by name

---

skytemple/module/dungeon_graphics/controller/tileset.py

The first rule of each variation was replaced after editing the chunks, because the first item of each icon view was selected which triggers the selection changed event.

Fix a bug on tileset rules

---

.github/workflows/build-mac.yml
.gitignore
installer/build-mac.sh
installer/skytemple-mac.spec
requirements-mac.txt
skytemple/core/ui_utils.py
skytemple/main.py

Adds build scripts for building Mac .app bundles with pyinstaller and a CI job.
Note that the bundle of the current master throws a runtime error:
```python
Traceback (most recent call last):
File "main.py", line 48, in <module>
File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.__dict__)
File "controller/main.py", line 43, in <module>
File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.__dict__)
File "core/ssb_debugger/manager.py", line 23, in <module>
File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
exec(bytecode, module.__dict__)
File …
```

Add packaging for Mac OS

---

skytemple/module/misc_graphics/controller/font.glade
skytemple/module/misc_graphics/controller/font.py
skytemple/module/misc_graphics/module.py

See SkyTemple/skytemple-files#39.
This provides: 
- support for editing monochrome font files, under the "Misc. Graphics" section;
- import and export of those files;
- basic character table viewer and editor.
Pull request mentioned above must be merged for this to work.

Basic support for monochrome font files

---

skytemple/module/misc_graphics/controller/font.py
skytemple/module/misc_graphics/controller/graphic_font.glade
skytemple/module/misc_graphics/controller/graphic_font.py
skytemple/module/misc_graphics/controller/zmappat.py
skytemple/module/misc_graphics/module.py

See pull request SkyTemple/skytemple-files#40.
UI support for graphic font files, under the "Misc. Graphics" section:
- an entry viewer;
- import/export buttons to edit images from those files.

Add support to edit graphic fonts

---

skytemple/module/misc_graphics/controller/font.py
skytemple/module/misc_graphics/controller/graphic_font.py
skytemple/module/misc_graphics/module.py

See SkyTemple/skytemple-files#41.
Adds UI support for editing banner font files, under:
- reuse of the UI for editing monochrome font files for editing/importing/exporting banner fonts.
Fixes the misc. graphics module to work with different font types accordingly.

Add support for editing banner fonts

---

.github/workflows/build-test-publish.yml
installer/skytemple-mac.spec
skytemple/controller/main.py
skytemple/main.py

* Fixed libSDL reference
* Removed the McMojave theme since it looks out of place on the redesigned Big Sur
* Disabled loading window position from config (causes the window to get stuck on a disconnected monitor, see #67)

Fix broken library reference on macOS, improvements for Big Sur

---

skytemple/module/dungeon/controller/floor.glade
skytemple/module/dungeon/controller/floor.py
skytemple/module/dungeon/module.py

See SkyTemple/skytemple-files#73
Adds UI support for editing ranks and no missions floor attributes (currently import/export is not supported for those attributes).
Some things have to be changed in order to provide multilanguage support (like the enumeration for the floor ranks).

Add Floor Ranks and No Missions attributes

---

skytemple/controller/settings.py

Right now, if there aren't any gtk themes installed the settings window crashes when hitting apply. I've added a null check to prevent this from happening.

Fix crash when trying to save settings with no themes installed

---

skytemple/module/dungeon/controller/fixed_rooms.py

Some entity ids can't be used in fixed rooms since they represent special tiles. Right now those are not shown in the list when editing a fixed room, but they are shown in the fixed entities list under "Fixed Rooms". I changed this so they aren't listed in that menu either.

Remove reserved ids from the fixed entity list

---

skytemple/module/dungeon/controller/floor.py

The previous check did not account for strings other than "0" that evaluated to 0 (such as "00").

Fix zero check in spawn weights

---

skytemple/core/events/impl/discord.py
skytemple/core/rom_project.py
skytemple/core/string_provider.py
skytemple/module/dungeon/controller/fixed.py
skytemple/module/dungeon/controller/fixed_rooms.py
skytemple/module/dungeon/controller/floor.glade
skytemple/module/dungeon/controller/floor.py
skytemple/module/monster/controller/monster.glade
skytemple/module/monster/controller/monster.py
skytemple/module/monster/module.py
skytemple/module/portrait/portrait_provider.py

See SkyTemple/skytemple-files#108
Adds UI support for the patch
Also fixes Sprite file size values when changing the sprite index, and N2M/M2N lists (that contain keys to sort recruited Pokémon by species name) when changing a Pokémon's name

Extend the Number of Pokémon entries

---

skytemple/core/rom_project.py
skytemple/data/locale/skytemple.pot
skytemple/module/rom/controller/main.py
skytemple/module/rom/controller/rom.glade
skytemple/module/rom/module.py

Allows editing the internal ROM name, ID and localized titles. Also see https://github.com/SkyTemple/skytemple-files/pull/119
~~The layout is broken because adding a line to one language resizes all of them, idk why~~ fixed

Initial support for editing ROM metadata (#182)

---

skytemple/module/lists/controller/guest_pokemon.glade
skytemple/module/lists/controller/guest_pokemon.py
skytemple/module/lists/module.py

Adds a new screen under "Lists" that can be used to change which dungeons add guest pokémon to your team when they are uncleared and what pokémon they add. The new screen also allows changing some dungeon data that was previously hardcoded by ID, such as which dungeons have Hidden Land-like restrictions active.
A potential improvement to the screen would be changing the guest columns to use a dropdown listing all the guest data entries instead of an integer.

Guest pokémon UI

---

skytemple/module/lists/controller/guest_pokemon.py

After pokémon icons were added to the guest pokémon menu in https://github.com/SkyTemple/skytemple/commit/9ab21deadc57e1775979c9be4a5fe616ac7799c7#diff-406df4a784b1d6c1871a44fb259f9008addd17dbf4fff9d76c4a54276794407a, SkyTemple crashes when trying to add a new entry because no value has been specified for the icon.
This change just sets a null value, so no icon will be displayed until the pokémon is changed or the view is reloaded.
Another option would be setting the icon of pokémon #0, but I don't know how to get the `idx` parameter that is needed for that. Feel free to do that instead if you prefer.

Quick fix for the guest pokémon list

---

skytemple/core/string_provider.py
skytemple/module/lists/controller/dungeon_interrupt.py
skytemple/module/lists/controller/iq.glade
skytemple/module/lists/controller/iq.py
skytemple/module/lists/controller/misc_settings.glade
skytemple/module/lists/controller/misc_settings.py
skytemple/module/lists/controller/tactics.glade
skytemple/module/lists/module.py

Also see skytemple/skytemple-files#166

IQ data editing

---

skytemple/module/map_bg/controller/bg.py
skytemple/module/map_bg/controller/bg_menu.py
skytemple/module/map_bg/controller/map_bg.glade
skytemple/module/map_bg/drawer.py

- Adds a "Rect" toggle button in menu bar to draw a filled rectangle for collision data and chunks instead of single points.
TODO: Use an icon instead of text for the "Rect" button.
- Also prevents from trying to set invalid tiles and chunks dimensions.

Rectangle draw option for background maps + dimension fix

---

installer/build-mac.sh

This seems to fix an issue that prevents a `libdesmume.so` built with the interface Meson script from being loaded (although it has the same name as before so maybe it was working due to PyInstaller magic in the background)

Fix dynamic library loader path variable name in Mac shell script

---

skytemple/module/monster/controller/monster.glade
skytemple/module/monster/controller/monster.py
skytemple/module/monster/module.py
skytemple/module/moves_items/controller/item_keys.glade
skytemple/module/moves_items/controller/item_keys.py
skytemple/module/moves_items/module.py

- Add an entry in General pokémon data to edit each one's idle type with the "ChangePokemonGroundAnim" patch. See Skytemple/skytemple-files#178
Import/Export should work with this value.
- Add a view to edit items sort keys under Items > Item Sort Keys.

UI Support for editing Idle Animation Type + Item Sort Keys

---

skytemple/core/sprite_provider.py
skytemple/module/sprite/controller/monster_sprite.py
skytemple/module/sprite/controller/object.glade
skytemple/module/sprite/controller/object.py
skytemple/module/sprite/module.py

Require https://github.com/SkyTemple/skytemple-rust/pull/6

Ability to import image as static ground object

---

skytemple/module/lists/controller/dungeon_interrupt.glade
skytemple/module/lists/controller/dungeon_interrupt.py

Adds an option in the UI to continue the music after exiting the floor.
See SkyTemple/skytemple-files#190.

Extend DungeonInterrupt to disable music fadeout

---

skytemple/module/portrait/controller/portrait.py

Originally reported in https://discord.com/channels/710190644152369162/712341752111169707/925893221643595776
This check shouldn't be done if the operation was cancelled, since `dialog.get_filename()` returns `None` in that case.

Fix error when pressing cancel in the export portraits dialogue

---

skytemple/module/script/module.py

Originally reported at: https://discord.com/channels/710190644152369162/712341752111169707/935004145621016576
String names and IDs shown in the "script scenes" screen are 2 places lower than they should.
For example, entry 195 should show "Wigglytuff's Guild" but instead shows "Crevice cave entrance". Some entries after, the ID of the "Wigglytuff's Guild" string is shown as #16532, when it should be #16534.
Strings start at 1, so you should add 1 to get the right string when accessing the list. Looks like you accidentally subtracted 1 instead.
I tested the change and the list now shows the right names and IDs.

Fix off-by-two error in strings in the scenes list

---

setup.py

Not having a comma here means concatenation in Python.

Make sure packaging dependency in setup.py is visible

---

skytemple/module/dungeon/controller/fixed_rooms.glade
skytemple/module/dungeon/controller/fixed_rooms.py

Allows edting the quantity of items placed on fixed rooms. Requires https://github.com/SkyTemple/skytemple-files/pull/226.

Allow editing fixed room item quantities

---

skytemple/module/dungeon/controller/fixed.glade
skytemple/module/dungeon/controller/fixed.py

There's three properties on the fixed room editor that have the opposite text, I've fixed them.
I also added a description for the one that disables certain traps that specifies which traps are affected by the setting.

Fix some fixed room properties' descriptions

---

skytemple/module/sprite/controller/object.glade

Just a very minor change. It also fix some potential embiguity. I didn't met any issue with this feature, nor (seemingly) others.
(ps: I'm trying to enhance my library to potentially replace the sprite import -- and will see soon on how to import simple animated object. Actually, being able to import and export object sprites as SpriteBot format is probably a good potential feature).

rewrite the message for static object import

---

skytemple/module/dungeon/controller/floor.py

Boolen inputs in floor data no longer work because of a bug in https://github.com/SkyTemple/skytemple/blob/b18408efe116130e2b89980aa2b2af9c53cf467c/skytemple/module/dungeon/controller/floor.py#L1971 (should be `val = val > 0`)
I reverted the commit that introduced this bug (https://github.com/SkyTemple/skytemple/commit/840d1fcc3e9b26cd1b0a67d51519cef5d208cf17) and added a simpler check instead. Unless there's some Python-specific stuff I'm not aware of, I think it should work. I tested it and it seems to be working fine now.

Fix floor data boolean inputs

---

skytemple/module/dungeon/controller/dungeon.glade
skytemple/module/dungeon/controller/dungeon.py
skytemple/module/dungeon/controller/floor.glade

Adds the recently documented "random movement chance" value to the dungeon restrictions screen.
I also added a help button for it and for the "enemy evolution enabled" flag, so the layout got reorganized a bit.
See also [the skytemple-files PR](https://github.com/SkyTemple/skytemple-files/pull/333).

Add random movement chance to dungeon restrictions

---

skytemple/module/sprite/controller/monster_sprite.py
skytemple/module/sprite/module.py
skytemple/module/spritecollab/module.py

This PR does two things:
1. Make sure every sprite are importable before importing them. This avoid importing part of the sprites, which cause issue.
2. In case the length of the sprites files are different, correct them by adding a new entry. It doesn’t import a sprite, but SkyTemple gracefully handle this, and this won’t prevent overwriting the sprite with another file.
edit: This does fix the problem of Juanma with Bowser

Better handling of sprite import error

---

.github/workflows/build-test-publish.yml

If this works, this will fix skytemple/skytemple-ssb-debugger#97

Update gvsbuild to fork with GTK3 patch for Windows

---

skytemple/core/logger.py
skytemple/core/sentry.py
skytemple/main.py

This gives me the ability to see how much new versions of SkyTemple are adopted.
You can see that for the dev release at the top it now shows adoption data, where previously no data was available.
This PR also fixes some logging related issues.

Sentry: Add session tracking

---

skytemple/controller/main.py

Previously the screen size would be saved to the settings when maximized, causing the program to forget the previous screen size and take up the whole screen when unmaximized.
This change fixes that by only storing the window size if it is not maximized which should return the window to its original size before it was maximized. Will need checking as my ST development installation is broken and I can't figure out how to fix it.

Small change to window size and maximized handling

---

skytemple/skytemple.glade

Adds credits for @Laioxy for their contributions to the JP symbols for pmdsky-debug.

Credit Laioxy

---

.github/workflows/build-test-publish.yml
installer/build-mac-arm.sh
installer/install-skytemple-rust.sh
installer/skytemple-mac.spec
skytemple/main.py

Adds a new GitHub Actions job to generate native binaries for ARM Macs using the new `macos-14` runner.
The most annoying difference is that all app bundles must be signed to run on Apple Silicon Macs (self-signed certificates are fine). PyInstaller already takes care of signing, but macOS refuses to load app bundles that were tampered with. Thus, we can't copy shell scripts or other files into the bundle after its creation anymore (I tried re-signing it, but I couldn't get it to work). The easiest workaround to get things running was adding code to setup environment variables in `main.py` instead, so that's what I did. I didn't include code from the wrapper script that reads the system language because SkyTemple seems to detect the language without it.
I didn't test every single feature …

Add native ARM macOS build

---

skytemple/module/strings/widget/strings.py

Small fix to string export mechanism - this ensures that strings which contain new lines aren't being written as actual new lines, which violates the "contains all strings in order, one per row" specification.
Comparison:
[old-str-export.csv](https://github.com/SkyTemple/skytemple/files/14952951/old-str-export.csv)
[new-str-export.csv](https://github.com/SkyTemple/skytemple/files/14952950/new-str-export.csv)

Fix issue with strings export

---

skytemple/module/patch/widget/asm.py

The wrong patch name would be shown in the error message when a custom ASM patch fails to load.

Fix incorrect error message

---

skytemple/data/locale/cs_CZ/LC_MESSAGES/skytemple.po
skytemple/module/portrait/widget/portrait.py

When importing portraits from multiple files, the information popup incorrect states that XX ranges from 0-40, which would mean a range of 41, when in reality, a mon can only have 40 portraits. This has been remedied to state a range of 0-39 for a total of 40 portraits.

Fix typo when importing portraits

---

skytemple/module/patch/module.py

Now that symbols have their own page, the Patches page no longer shows symbols or functions. As such, I've removed the information string saying that it does.

Remove line of info from Patches line

---

skytemple/module/monster/widget/monster.py

Change the UI to use SpriteSizeInMonsterData as the reference for showing Sprite Size and Sprite File Size.
This should not be merged before Skytemple/skytemple-files#527.

Use Sprite Size patch

---

skytemple/core/error_handler.py

The SpriteCollab browser was just passing a normal exception, not an `exc_info` tuple, to the `display_error` function. This updates the code so that this is now supported. `cgitb` still errors out but the fallbacks work, so it's "good enough".
This also removes usage of `cgitb`, since that will be removed in Python 3.13

Support raw exceptions in error display code, remove cgitb

---

skytemple/module/strings/widget/strings.py

Fixes #812. When exporting strings to a CSV, actual linebreaks are swapped for `\n`, as shown here:
```
wr.writerows([[x.replace("\n", "\\n")] for x in self._str.strings])
```
The issue arises from the fact that this is not undone when importing, meaning the linebreaks stay as `\n` instead of actual linebreaks. This can be undone by adding a `replace("\\n", "\n")` to the code relevant to importing, causing the new code to look like this:
```
strings.append(row[0].replace("\\n", "\n"))
```
This should cause linebreaks to be imported properly instead of as `\n`.
I'm unable to build SkyTemple to see if this works myself, but I'm hoping my logic makes sense.

Fix linebreaks when importing strings
