skytemple/module/dungeon/module.py, skytemple/module/dungeon_graphics/controller/dungeon_bg.py, skytemple/module/map_bg/controller/bg.py
- Fix the mappa_g.bin file not being updated when exporting to other floors.
- Fix the behaviour when try to edit tiles/chunks out of the drawing area.
=> Fix export floors not updating mappa_g.bin and background editing.

skytemple/controller/main.py, skytemple/controller/tilequant.py, skytemple/module/bgp/controller/bgp.py, skytemple/module/dungeon/controller/floor.py, skytemple/module/dungeon_graphics/controller/bg_menu.py, skytemple/module/dungeon_graphics/controller/tileset.py, skytemple/module/map_bg/controller/bg_menu.py, skytemple/module/misc_graphics/controller/font.py, skytemple/module/misc_graphics/controller/graphic_font.py, skytemple/module/misc_graphics/controller/w16.py, skytemple/module/misc_graphics/controller/wte_wtu.py, skytemple/module/misc_graphics/controller/zmappat.py, skytemple/module/monster/controller/level_up.py, skytemple/module/monster/controller/monster.py, skytemple/module/portrait/controller/portrait.py
=> Switch to native file choosers (where possible)

skytemple/controller/main.py, skytemple/controller/tilequant.py, skytemple/module/bgp/controller/bgp.py, skytemple/module/dungeon/controller/floor.py, skytemple/module/dungeon_graphics/controller/bg_menu.py, skytemple/module/dungeon_graphics/controller/tileset.py, skytemple/module/map_bg/controller/bg_menu.py, skytemple/module/misc_graphics/controller/font.py, skytemple/module/misc_graphics/controller/graphic_font.py, skytemple/module/misc_graphics/controller/w16.py, skytemple/module/misc_graphics/controller/wte_wtu.py, skytemple/module/misc_graphics/controller/zmappat.py, skytemple/module/monster/controller/level_up.py, skytemple/module/monster/controller/monster.py, skytemple/module/portrait/controller/portrait.py
=> Replace all response types with the one used in a native file chooser

skytemple/module/lists/controller/starters_list.glade, skytemple/module/lists/controller/starters_list.py, skytemple/module/lists/module.py
See SkyTemple/skytemple-files#43.
=> Make default starters species editable

skytemple/module/dungeon/controller/fixed.py, skytemple/module/misc_graphics/controller/cart_removed.glade, skytemple/module/misc_graphics/controller/cart_removed.py, skytemple/module/misc_graphics/controller/chr.glade, skytemple/module/misc_graphics/controller/chr.py, skytemple/module/misc_graphics/module.py
See SkyTemple/skytemple-files#57.
Adds UI support for editing chr and the cartridge removed image, under the Misc. Graphics section (import and export).
=> Add support for chr files + cartridge removed image

skytemple/module/lists/controller/item_effects.glade, skytemple/module/lists/controller/item_effects.py, skytemple/module/lists/controller/move_effects.glade, skytemple/module/lists/controller/move_effects.py, skytemple/module/lists/module.py
See Skytemple/skytemple-files#79
Adds UI support to edit, change and inject binary code for move effects.
See also https://github.com/irdkwia/eos-move-effects for testing and creating custom move effects.
=> Adds UI support for move effects manipulation.

skytemple/module/sprite/controller/monster_sprite.glade, skytemple/module/sprite/controller/monster_sprite.py
Related to: https://github.com/SkyTemple/skytemple-files/pull/86
=> Add checkbox for import/export with zip

skytemple/data/locale/skytemple.pot, skytemple/module/lists/controller/move_effects.glade, skytemple/module/lists/controller/move_effects.py
See SkyTemple/skytemple-files#90
=> Add a button to add the other unused moves to the move effects list

skytemple/data/locale/skytemple.pot, skytemple/module/monster/controller/monster.glade, skytemple/module/monster/controller/monster.py
Related to SkyTemple/skytemple-files#101
Update description of evolution parameters, chest drop rates and can throw items.
=> Update Monster UI

installer/build-mac.sh
=> Fix language auto-detection on Mac

skytemple/module/monster/controller/monster.glade, skytemple/module/monster/controller/monster.py, skytemple/module/monster/module.py
Adds UI support for that patch: SkyTemple/skytemple-files#104
You can change the values under the Evolution tab for each Pokémon (Import and Export for those values currently don't work).
Also tells how the game uses some of the evolution related values.
=> Add a patch to change the game evolution system.

skytemple/module/lists/controller/sp_effects.glade, skytemple/module/lists/controller/sp_effects.py, skytemple/module/lists/module.py
See SkyTemple/skytemple-files#116
Adds UI support for editing special process data.
=> Special Process Code patch

skytemple/module/dungeon_graphics/controller/dungeon_bg.py, skytemple/module/dungeon_graphics/controller/main.py, skytemple/module/dungeon_graphics/controller/tileset.py, skytemple/module/dungeon_graphics/controller/trp_itm_img.glade, skytemple/module/dungeon_graphics/controller/trp_itm_img.py, skytemple/module/dungeon_graphics/module.py
=> Trap and Item Icons

skytemple/module/dungeon/controller/floor.glade, skytemple/module/dungeon/controller/floor.py
Please check whether I messed something up.
See also SkyTemple Files PR: skytemple/skytemple-files#164
=> Fix IQ booster bytes for floor data

skytemple/module/lists/controller/iq.glade, skytemple/module/lists/controller/iq.py
See also skytemple/skytemple-files#169
=> skytemple/skytemple-files#168: IQ Skill restrictions

skytemple/module/dungeon/controller/floor.glade
I finally decided to properly test this
=> Rename unknown item lists in dungeons

skytemple/module/dungeon/controller/floor.glade
=> Rename unknown item lists in floor export dialogue

skytemple/core/mapbg_util/map_tileset_overlay.py, skytemple/module/dungeon_graphics/chunk_editor_data_provider/tile_graphics_provider.py, skytemple/module/dungeon_graphics/chunk_editor_data_provider/tile_palettes_provider.py, skytemple/module/lists/controller/world_map.py, skytemple/module/lists/world_map_drawer.py, skytemple/module/map_bg/chunk_editor_data_provider/tile_graphics_provider.py, skytemple/module/map_bg/chunk_editor_data_provider/tile_palettes_provider.py, skytemple/module/map_bg/controller/bg.py, skytemple/module/map_bg/controller/bg_menu.py, skytemple/module/map_bg/controller/bg_menu_dialogs/map_width_height.py, skytemple/module/map_bg/drawer.py, skytemple/module/map_bg/module.py, skytemple/module/map_bg/script/add_created_with_logo.py, skytemple/module/monster/module.py, skytemple/module/portrait/controller/portrait.py, skytemple/module/portrait/portrait_provider.py, skytemple/module/script/controller/dialog/pos_mark_editor.py, skytemple/module/script/controller/ssa.py, skytemple/module/script/drawer.py, skytemple/module/script/module.py, skytemple/module/tiled_img/chunk_editor_data_provider/tile_graphics_provider.py, skytemple/module/tiled_img/chunk_editor_data_provider/tile_palettes_provider.py, skytemple/module/tiled_img/dialog_controller/chunk_editor.py, skytemple/module/tiled_img/drawer_tiled.py
Support for the generic protocols for bg_list.dat, BMA, BPC, BPL, BPA.
See also https://github.com/SkyTemple/skytemple-files/pull/202
=> Native ground bgs

skytemple/core/rom_project.py
See https://github.com/SkyTemple/skytemple-files/pull/204
=> Changes for new Pmd2Binary blocks

installer/build-mac.sh
It's impossible for me to test this, unfortunately
=> Attempt to fix dylib loading on Monterey

installer/download-windows-dependencies.sh, requirements-mac-windows.txt, requirements.txt, setup.py, skytemple/core/model_context.py, skytemple/core/rom_project.py
See https://github.com/SkyTemple/skytemple-files/pull/251
=> Compatibility with static pmdsky-debug-py

skytemple/module/moves_items/controller/item.glade
I finally got around to testing these and I can now confirm what each one of them does exactly.
See also [the skytemple-files PR](https://github.com/SkyTemple/skytemple-files/pull/326).
=> Update item AI flags description

skytemple/core/sprite_provider.py, skytemple/module/monster/controller/monster.py, skytemple/module/sprite/controller/monster_sprite.py
See https://github.com/SkyTemple/skytemple-rust/pull/43
=> update for pmd_wan 5.1.1

installer/download-windows-dependencies.sh, requirements-mac-windows.txt, setup.py, skytemple/core/sprite_provider.py, skytemple/module/monster/controller/monster.py, skytemple/module/sprite/controller/monster_sprite.py
This also moves the sprite size correction algorithm to SkyTemple Files.
See https://github.com/SkyTemple/skytemple-files/commit/83021819
=> Update to SkyTemple Files 1.5.0

.github/workflows/build-test-publish.yml, installer/build-mac.sh
Wanted to take a look at how compilation work on Mac.
I’ll follow up with a windows fix too.
=> Fix CI for Mac

skytemple/module/map_bg/controller/bg_menu.py, skytemple/module/script/controller/main.py
=> Fix issues related to BPAs

skytemple/module/spritecollab/controller/browser.py
=> Fix SpriteCollab Browser Issues

skytemple/module/dungeon/fixed_room_entity_renderer/full_map.py
=> Fix bounds check for special items off by one

skytemple/module/moves_items/controller/move.glade, skytemple/module/moves_items/controller/move.py
See also:
- https://github.com/SkyTemple/skytemple-files/pull/388
- https://github.com/SkyTemple/skytemple-rust/pull/61
=> Update unknown values in move data

skytemple/module/dungeon/controller/floor.glade, skytemple/module/dungeon/controller/floor.py
See https://github.com/SkyTemple/skytemple-files/pull/394
closes SkyTemple/skytemple-files/issues/381
=>  Editable Monster House Spawn weights

.github/workflows/build-test-publish.yml, docs/plugin_dev.rst, docs/user_manual.rst, installer/build-windows.ps1, mypy.ini, requirements-mac-windows.txt, requirements.txt, setup.py, skytemple/core/modules.py, skytemple/core/plugin_loader/__init__.py, skytemple/core/plugin_loader/finder.py, skytemple/core/plugin_loader/loader.py, skytemple/core/settings.py, skytemple/main.py
Will close #610. I will write the documentation later.
=> Plugin Loader

skytemple/module/dungeon/controller/floor.py
Part of https://github.com/SkyTemple/skytemple-files/pull/466
=> Add NegativeEnemyDensity patch

skytemple/core/canvas_scale.py, skytemple/module/dungeon/controller/fixed.py, skytemple/module/dungeon/controller/floor.py, skytemple/module/dungeon_graphics/controller/dungeon_bg.py, skytemple/module/map_bg/controller/bg.py, skytemple/module/script/controller/ssa.py
=> Fix #713: Limit scaling

skytemple/controller/settings.py
Fixes an incorrect link that's meant to lead to the Crowdin page.
=> Minor typo in Settings

org.skytemple.SkyTemple.appdata.xml, skytemple/module/lists/widget/iq.py
Compatibility with https://github.com/SkyTemple/skytemple-files/pull/495
Also bumps version; as the PR above will bump the SkyTemple Files version.
=> Compatibility with text string improvements

skytemple/data/locale/cs_CZ/LC_MESSAGES/skytemple.po, skytemple/data/locale/de_DE/LC_MESSAGES/skytemple.po, skytemple/data/locale/es_ES/LC_MESSAGES/skytemple.po, skytemple/data/locale/fr_FR/LC_MESSAGES/skytemple.po, skytemple/data/locale/it_IT/LC_MESSAGES/skytemple.po, skytemple/data/locale/ja_JP/LC_MESSAGES/skytemple.po, skytemple/data/locale/nl_NL/LC_MESSAGES/skytemple.po, skytemple/data/locale/pt_BR/LC_MESSAGES/skytemple.po, skytemple/data/locale/pt_PT/LC_MESSAGES/skytemple.po, skytemple/data/locale/ru_RU/LC_MESSAGES/skytemple.po, skytemple/data/locale/skytemple.pot, skytemple/data/locale/vi_VN/LC_MESSAGES/skytemple.po, skytemple/data/locale/zh_CN/LC_MESSAGES/skytemple.po, skytemple/data/locale/zh_TW/LC_MESSAGES/skytemple.po, skytemple/skytemple.glade
Updates my username everywhere on the repo.
I've also updated my entry in the credits to "patches + contributions", since I've also helped develop some features, like the recent symbols editor. I hope that's ok.
Other related PRs:
- https://github.com/SkyTemple/skytemple-files/pull/521
- https://github.com/SkyTemple/skytemple-randomizer/pull/212
- https://github.com/SkyTemple/skytemple-ssb-debugger/pull/136
=> Username update

skytemple/data/widget/monster/main.ui, skytemple/data/widget/monster/monster.ui, skytemple/module/monster/module.py, skytemple/module/monster/widget/main.py, skytemple/module/monster/widget/monster.py
m_attack.bin is also used in Dungeon Mode, so the maximum amount of blocks in VRAM must be computed with that in mind
This should be merged at the same time as Skytemple/skytemple-files#530
=> Improvement on Sprite Size Management

skytemple/module/patch/widget/asm.py
Adds UI support for the OutdatedPatchDependency exception added in https://github.com/SkyTemple/skytemple-files/pull/557.
Needed for https://github.com/SkyTemple/skytemple-files/pull/556.
I also took the liberty of making the ROM not save and reload if an error is raised (including this one) after a patch is applied. It's weird that SkyTemple says "Patches failed to apply, the ROM might be corrupted now" then saves the ROM lol
It won't let you apply more patches if the ROM is unsaved anyway.
=> Support for OutdatedPatchDependencyError
